# Main configuration file for programs directory example
# Process definitions are separated into the programs/ directory

# Global settings
use_os_env = true
env = ["DEMO_ENV=production", "SERVICE_VERSION=1.0.0"]

# Programs directory to load process definitions from
programs_directory = "programs"

[log]
dir = "/tmp/provisr-programs-demo"
max_size_mb = 5
max_backups = 2
max_age_days = 3
compress = true

[server]
listen = "127.0.0.1:8080"
base_path = "/api"

# Persistent store has been removed in recent versions; PID files and in-memory state are used for recovery.

[metrics] 
enabled = true
listen = "127.0.0.1:9090"

# Groups that reference processes defined in programs/ directory
[[groups]]
name = "web-services"
members = ["frontend", "api-server"]

[[groups]]
name = "background-tasks"
members = ["worker", "scheduler"]

[[groups]]
name = "infrastructure"
members = ["database", "cache-redis"]

[[groups]]
name = "all-services"
members = ["database", "cache-redis", "api-server", "frontend", "scheduler", "worker"]
