# Detached programs directory demo configuration

# Use OS env and set a couple of demo variables
use_os_env = true
env = ["DEMO_ENV=production", "SERVICE_VERSION=1.0.0"]

# Load processes from this directory (relative to this file)
programs_directory = "programs"

[log]
dir = "./provisr-programs-detach-demo"
max_size_mb = 5
max_backups = 2
max_age_days = 3
compress = true

[server]
# Use a non-default port to avoid conflicts with other examples
listen = "127.0.0.1:18080"
base_path = "/api"

# Persistent store has been removed in recent versions; PID files and in-memory state are used for recovery.

[metrics]
enabled = false
