# Sample configuration for the embedded_config_file example
# This file is colocated with the example so it can be run standalone.

# Global environment for all processes
env = ["GLOBAL_NAME=provisr", "SHARED_PORT=9000", "CHAIN=${GLOBAL_NAME}-x"]

[log]
dir = "/tmp/provisr-logs"
max_size_mb = 10
max_backups = 3
max_age_days = 7
compress = false

[[processes]]
name = "web"
command = "python3 -m http.server 18080"
workdir = "/tmp"
env = ["ENV=prod", "PORT=18080"]
pidfile = "/tmp/web.pid"
retries = 3
retry_interval = "500ms"
startsecs = "2s"
autorestart = true
restart_interval = "1s"
instances = 1
  [processes.log]
  stdout = "/tmp/provisr-logs/web.stdout.log"
  stderr = "/tmp/provisr-logs/web.stderr.log"
  [[processes.detectors]]
  type = "pidfile"
  path = "/tmp/web.pid"
  [[processes.detectors]]
  type = "command"
  command = "pgrep -f 'python3 -m http.server 18080' >/dev/null"

[[processes]]
name = "worker"
command = "sh -c 'while true; do echo working; sleep 1; done'"
retries = 1
retry_interval = "300ms"
startsecs = "500ms"
autorestart = true
restart_interval = "1s"
instances = 1
  [[processes.detectors]]
  type = "command"
  command = "pgrep -f 'echo working' >/dev/null"

# Optional: a simple cron job that prints occasionally (safe to ignore)
[[processes]]
name = "cron-clean"
command = "sh -c 'echo cleaning'"
schedule = "@every 5s"
singleton = true
