# Sample configuration for the embedded_config_file example
# Process definitions are now in the programs/ directory

# Global environment for all processes
env = ["GLOBAL_NAME=provisr", "SHARED_PORT=9000", "CHAIN=${GLOBAL_NAME}-x"]

# Programs directory (relative to this config file)
programs_directory = "programs"

[server]
listen = "127.0.0.1:8080"
base_path = "/api"

[log]
dir = "/tmp/provisr-logs"
max_size_mb = 10
max_backups = 3
max_age_days = 7
compress = false
