type: process
spec:
  name: database
  command: "sh -c 'echo \"Database starting...\"; i=1; while true; do echo \"[$(date)] DB: Processing query #$i\"; i=$((i+1)); sleep 4; done'"
  priority: 1
  retry_count: 3
  retry_interval: 2s
  start_duration: 1s
  auto_restart: true
  restart_interval: 10s
  instances: 1
  env:
    - "DB_PORT=5432"
    - "DB_NAME=myapp"
    - "MAX_CONNECTIONS=100"
  log:
    dir: "/tmp/provisr-programs-demo/database"
    stdout: "/tmp/provisr-programs-demo/database/database.out.log"
    stderr: "/tmp/provisr-programs-demo/database/database.err.log"
    max_size_mb: 50
    max_backups: 10
