type = "process"
[spec]
name = "test-service"
command = "bash -c 'while true; do echo \"Test service running...\"; sleep 5; done'"
priority = 1
retry_count = 2
retry_interval = "1s"
start_duration = "1s"
autorestart = true
restart_interval = "1s"
instances = 1
env = ["SERVICE_NAME=test"]

[spec.log]
dir = "/tmp/provisr-programs-demo/test-service"
stdout = "/tmp/provisr-programs-demo/test-service/service.out.log"
stderr = "/tmp/provisr-programs-demo/test-service/service.err.log"
