# Cleanup cron job - runs every 30 seconds
name = "cleanup"
command = "echo \"[$(date)] Cleaning temp files...\"; touch /tmp/provisr-demo-cleaned; echo \"[$(date)] Cleanup completed\""
priority = 0
schedule = "@every 30s"
singleton = true