# Cleanup process example (can be triggered manually or by group)
name = "cleanup"
command = "sh -c 'echo [$(date)] Cleaning temp files...; touch /tmp/provisr-demo-cleaned; echo [$(date)] Cleanup completed'"
priority = 0
autorestart = false
