# Cron job in unified format (type/spec)
type = "cronjob"
[spec]
name = "cron-clean"
schedule = "@every 10s"
concurrency_policy = "Forbid"

[spec.job_template]
name = "cron-clean"
# Demonstrate reading environment variables from config/config.toml (GLOBAL_NAME, SHARED_PORT, CHAIN)
command = "sh -c 'echo [$(date)] cleaning from cron: GLOBAL_NAME=$GLOBAL_NAME SHARED_PORT=$SHARED_PORT CHAIN=$CHAIN'"
