# Long running sleep process
type = "process"
[spec]
name = "long-sleeper"
command = "sleep 300"  # 5 minutes
priority = 10
retries = 2
auto_restart = true
restart_interval = "1s"
startsecs = "0.5s"
instances = 1

[spec.log]
dir = "/tmp/provisr-logs"

# Process detectors
[[spec.detectors]]
type = "command"
command = "pgrep -f 'sleep 300'"
