# Long running sleep process
name = "long-sleeper"
command = "sleep 300"  # 5 minutes
priority = 10
retries = 2
autorestart = true
restart_interval = "1s"
startsecs = "0.5s"
instances = 1

[log]
dir = "/tmp/provisr-logs"

# Process detectors
[[detectors]]
type = "command"
command = "pgrep -f 'sleep 300'"